pagopa/selfcare-external-api-backend

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/PartyConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionController.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerTest.java
* add filter on product to getInstitutions api
* add filter on product to getInstitutions api
* add add log
Co-authored-by: USERSAD\bgalgamu <bgalgamu@emeal.nttdata.com>
> Feature/selc 1425 (#9)

- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java
* fixed merge on products having multiple role on product
* fixed merge on products having multiple role on product
Co-authored-by: USERSAD\bgalgamu <bgalgamu@emeal.nttdata.com>
> release-uat

- app/src/main/resources/swagger/api-docs.json
- app/src/test/java/it/pagopa/selfcare/external_api/web/config/SwaggerConfigTest.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/ProductsConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/client/ProductsRestClient.java
- connector/rest/src/main/resources/config/products-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/client/ProductsRestClientTest.java
- connector/rest/src/test/resources/stubs/products/mappings/getProduct_fullyValued.json
- core/src/main/java/it/pagopa/selfcare/external_api/core/ProductService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/ProductServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/ProductServiceImplTest.java
- pom.xml
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/ProductController.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/ProductControllerTest.java
> Adding Get Product api from Id

- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/MsPartyRegistryProxyConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/PartyConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/institutions/InstitutionResource.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/institutions/Origin.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/MsPartyRegistryProxyConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/client/MsPartyRegistryProxyRestClient.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/MsPartyRegistryProxyConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/client/MsPartyRegistryProxyRestClientTest.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/OnboardingMapper.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/model/mapper/InstitutionMapperTest.java
Reverts pagopa/selfcare-external-api-backend#75
> revert - uat merge

- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardingResponseData.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/InstitutionMapper.java
Retrieve parentDescription straight from onboardingResponseData
Ms-core previously didn't return this field
> Retrieve correct parentDescription from core

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/institutions/InstitutionInfo.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImpl.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/institutions/InstitutionResource.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/institutions/RootParentResource.java
- web/src/main/resources/swagger/swagger_en.properties
Change InstitutionResource parentDescription property to rootParent
The new root Parent will contain a reference to a subInstitution parent. It's ID and Description
> Feat: change parentDescription to rootParent in InstitutionResource

- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardingResponseData.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImpl.java
- connector/rest/src/test/resources/stubs/party-process/mappings/getOnBoardingInfo_fullyValued.json
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/institutions/InstitutionResource.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/InstitutionResourceMapper.java
Update getInstitutions /institutions response adding root parent id
On entity Institution has been added this new field - rootParentId - in order to retrieve infos about cebtral institution in case of AOO/UO
I have run microservice locally aiming to dev invironment and tested the specific api
> Update getInstitutions response adding root parent id

- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/PartyConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/client/PartyProcessRestClient.java
- connector/rest/src/main/resources/config/party-process-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/client/PartyProcessRestClientTest.java
- connector/rest/src/test/resources/stubs/party-process/mappings/createInstitution.json
- core/src/main/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImplTest.java
Added createInstitution method for no IPA
This change was necessary to avoid null externalId into institution object
I have deployed the feature branch in dev and tested the api **/onboarding** POST
> Added createInstitution method for no IPA

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/user/ProductDetails.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/user/UserDetailsWrapper.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/UserService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/UserServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/UserController.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/UserInfoResourceMapper.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/onboarding/OnboardedProductResource.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/user/UserDetailsResource.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/UserControllerTest.java
add api to retrieve user's specific onboarded ProductDetails
External interceptor needs to retrieve the date of the user's onboarding to the product
> add api to retrieve user's specific onboarded ProductDetails

- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/OnboardingControllerTest.java
- web/src/test/resources/stubs/invalidSaOnboardingProductDto.json
Fix junit tests for onboarding SA
> Fix junit tests for onboarding SA

- app/src/main/resources/swagger/api-docs.json
- pom.xml
Changed common version from 2.4.7 to 2.4.9 in order to manage new institution type AS
> [SELC-3219] feat: update common version 

- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/model/onboarding/PdaInstitutionSeed.java
Fixed task SELC-3289 adding required parameter injectionInstitutionType for api of institution from pda on ms-core.
Added required parameter injectionInstitutionType.
The parameter is required from API to persist properly the institution.
locally
> Added parameter injectionInstitutionType SELC-3289

- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/model/institution/InstitutionResponse.java
added subunitCode and subunitType to InstitutionResponse
The fields subunitCode and subunitType are required for filter in PDA import tool.
local environment
> [SELC-3354] Feat: added subunitCode and subunitType to InstitutionResponse

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- .devops/pnpg-code-review-pipelines.yml
- .devops/pnpg-deploy-pipelines.yml
- Dockerfile
- connector/azure-storage/src/test/java/it/pagopa/selfcare/external_api/connector/azure_storage/AzureBlobClientTest.java
- pom.xml
- updated starter-parent version from 0.0.2 to 0.0.3 for jdk 17 update
- updated pipelines from 1.11 to 1.17
- updated dockerfile image
These updates are necessary as there is a need to upgrade to java 17
- Build was done locally
- the microservice was started locally and some APIs were invoked
> [SELC -3371] feat: updated pipelines version, starter parent version and Dockerfile

- helm/values-dev.yaml
Set host on Kubernetes ingress
Wildcard would not work anymore when cluster will be upgraded to a newer version
> [SELC-3339] Set host on ingress (DEV)

- helm/values-uat.yaml
- helm/values.yaml
Set host on Kubernetes ingress
Wildcard would not work anymore when cluster will be upgraded to a newer version
> [SELC-3340] Set host on ingress (UAT)

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- helm/values.yaml
Set host on Kubernetes ingress
Wildcard would not work anymore when cluster will be upgraded to a newer version
> [SELC-3341] Set host on ingress (PROD)

- .github/workflows/release_open_api.yml
Update step for check breaking changes into github action.
Changed action to retrieve breaking changes into api-docs.
> [SELC-3516] fix: update step for detect breaking changes into github action

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/institutions/InstitutionResource.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/products/ProductResource.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/user/UserResource.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/model/institutions/InstitutionResourceTest.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/model/product/ProductResourceTest.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/model/user/UserResourceTest.java
Added required constraints to user, product and institution resource
In order to give more details in API documentation, some constraint validations have been added into resource
> [SELC-3684] feat: added required constraints to user, product and institution resource

- .gitignore
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/MsCoreConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/OnboardingMsConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/InstitutionOnboarding.java
- connector/rest/docs/openapi/api-selfcare-core-docs.json
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/pom.xml
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/OnboardingMsConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/client/MsCoreInstitutionApiClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/client/MsOnboardingTokenControllerApi.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/config/MsOnboardingApiClientConfig.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/InstitutionMapper.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/TokenMapper.java
- connector/rest/src/main/resources/config/ms-core-rest-client.properties
- connector/rest/src/main/resources/config/ms-onboarding-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/OnboardingMsConnectorImplTest.java
Added rest client for onboarding-ms and ms-core using openapi generator
> [SELC-4032] feat: ms-onboarding e ms core openapi

- app/src/main/resources/swagger/api-docs.json
- core/src/main/java/it/pagopa/selfcare/external_api/core/ContractService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/ContractServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/ContractServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionController.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerV2Test.java
* Added a new endpoint, version v2 GET institutions/{institutionId}/contract, which is designed to return file contract.
* This endpoint triggers the new onboarding service
The existing onboarding process redirect to old onboarding service.
> [SELC-4032] feat: Introduce New v2 GET contract

- connector/rest/src/main/resources/config/ms-onboarding-rest-client.properties
- helm/values-dev.yaml
- helm/values-uat.yaml
> ops: set onboarding ms url env

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/MsOnboardingMsConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/OnboardingMsConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/OnboardingMsConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/client/MsOnboardingControllerApi.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/config/MsOnboardingApiClientConfig.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/OnboardingMapper.java
- connector/rest/src/main/resources/config/ms-onboarding-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/OnboardingMsConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/OnboardingService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/OnboardingController.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/OnboardingV2Controller.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/OnboardingV2ControllerTest.java
Added a new endpoint, version v2 GET /onboarding, which is designed to process onboarding. This endpoint triggers the new onboarding service
The existing onboarding process redirects to old onboarding service.
> [SELC-4007] feat: added new API /v2/onboarding

- .github/workflows/opex_api_pnpg.yml
- .identity/.terraform.lock.hcl
- .opex/api-selfcare-external-api-pnpg/env/prod/backend.ini
- .opex/api-selfcare-external-api-pnpg/env/prod/backend.tfvars
- .opex/api-selfcare-external-api-pnpg/env/prod/config.yaml
- .opex/api-selfcare-external-api-pnpg/env/prod/terraform.tfvars
> [SELC-2952] add Opex PNPG

- .opex/api-selfcare-external-api-pnpg/env/prod/config.yaml
- .opex/api-selfcare-external-api/env/prod/config.yaml
> [SELC-2952] fix alert

- .opex/api-selfcare-external-api-pnpg/env/prod/config.yaml
- .opex/api-selfcare-external-api/env/prod/config.yaml
> [SELC-2952] fix Endpoints configuration

- app/src/main/resources/swagger/api-docs.json
- app/src/test/java/it/pagopa/selfcare/external_api/web/config/SwaggerConfigTest.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/MsCoreConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/OnboardingMsConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/token/ProductToken.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/token/TokenOnboardedUsers.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/user/InstitutionProducts.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/user/RelationshipState.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/user/UserProducts.java
- connector/rest/docs/openapi/api-selfcare-core-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/OnboardingMsConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/client/MsCoreUserApiClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/config/MsCoreRestClientConfig.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/TokenMapper.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/TokenUserMapper.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/UserProductMapper.java
- connector/rest/src/main/resources/config/ms-core-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/TokenService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/TokenServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/TokenServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/TokenController.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/TokenResourceMapper.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/tokens/LegalsResource.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/tokens/TokenResource.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/tokens/TokensResource.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/TokenControllerTest.java
Added new API to retrieve tokens by productId
This API has been added into external-api after separation of onboading business logic from ms-core microservice.
I have run the microservice locally and tested the new API **GET /tokens/products/{productId}**
> [SELC-4086] feat: Added new API to retrieve tokens by productId

- .dockerignore
- .github/workflows/pr_ms.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_ms_pnpg.yml
- Dockerfile.new
- Dockerfile.new.dockerignore
- pom.xml
Add workflows
Migrating to container apps
> [EC-152] Add microservice pipelines

- helm/pnpg/values-dev.yaml
- helm/pnpg/values-uat.yaml
- helm/values-uat.yaml
> ops: onboarding ms url pnpg

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/token/TokenOnboardedUsers.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/OnboardingMapper.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/TokenMapper.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/TokenServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/TokenServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/TokenResourceMapper.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/tokens/TokenResource.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/TokenControllerTest.java
* Added right mapping of legals list on getTokens endpoint removing unuseful call to ms-core
* Update onboarding-ms openapi and mapper 
getTokens endpoint performed an unuseful call to ms-core retrieving data just owned.
> [SELC-4306] fix: mapping legals and institutionId on getTokens

- .github/workflows/pr_ms.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_ms_pnpg.yml
- Dockerfile.new
- infra/container_apps/.terraform.lock.hcl
- infra/container_apps/README.md
- infra/container_apps/env/dev-pnpg/backend.ini
- infra/container_apps/env/dev-pnpg/backend.tfvars
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/backend.ini
- infra/container_apps/env/dev/backend.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/backend.ini
- infra/container_apps/env/prod-pnpg/backend.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/backend.ini
- infra/container_apps/env/prod/backend.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/backend.ini
- infra/container_apps/env/uat-pnpg/backend.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/backend.ini
- infra/container_apps/env/uat/backend.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/main.tf
- infra/container_apps/terraform.sh
- infra/container_apps/variables.tf
Add Terraform moudle to deploy microservice on Container App
Migration to Container Apps
> [EC-121] Add Container App infrastructure

- .github/workflows/release_ms.yml
- .github/workflows/release_ms_pnpg.yml
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
JWT_TOKEN_PUBLIC_KEY misses as env variable
> [EC-121] fix: added JWT_TOKEN_PUBLIC_KEY as secret

- .github/workflows/release_open_api.yml
- helm/pnpg/values-dev.yaml
- helm/pnpg/values-uat.yaml
- helm/values-uat.yaml
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
Remove workload_profile_name variables because is default on terraform module
Change PNPG dns suffix url
Migration to new Container Apps environment with Workload profile
> chore: Workload profiles migration PNPG

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/PartyConnector.java
- connector/rest/docs/openapi/api-selfcare-user-docs.json
- connector/rest/pom.xml
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/client/UserApiRestClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/config/UserApiRestClientConfig.java
- connector/rest/src/main/resources/config/user-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImplTest.java
- connector/rest/src/test/resources/stubs/PartyConnectorImplTest/user_institutions_to_product.json
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java
- helm/pnpg/values-dev.yaml
- helm/pnpg/values-prod.yaml
- helm/pnpg/values-uat.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerV2Test.java
Added v2 for getInstitutionUserProducts
With separation of user's business logic from ms-core, this API has to interact with the new microservice to retrieve user data
I have run the microservice locally
> [SELC-4601] feat: added v2 for getInstitutionUserProducts

- helm/pnpg/values-dev.yaml
- helm/pnpg/values-prod.yaml
- helm/pnpg/values-uat.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
> cherry-pick releases 1.0.1

- .github/workflows/pr_ms.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_ms_pnpg.yml
- app/src/main/resources/swagger/api-docs.json
* Added branches reference to pr pipeline
* Refactor paths on release pipeline
Pipeline are not triggered
> chore: refactor release and pr pipeline

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/UserMsConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/UserMsConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/UserMsConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/UserService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/UserServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/UserV2Controller.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/UserControllerV2Test.java
Added V2 version of user's onboarded product retrieval api
Migrate the api to use the new user-ms instead of ms-core
Locally deployed and tested
> [SELC-4598] feat: Added V2 for getUserProductDetails api

- connector/rest/src/main/resources/config/ms-core-rest-client.properties
- connector/rest/src/main/resources/config/ms-party-registry-proxy-client.properties
- connector/rest/src/main/resources/config/products-rest-client.properties
- connector/rest/src/main/resources/config/user-registry-rest-client.properties
- Added  errorDecoder in feign client config
When feign client api throws an exception we need to catch this exception to transform it into another
> hotfix: add errorDecoder in feign client config

- .github/workflows/pr_ms.yml
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/decoder/FeignErrorDecoder.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/client/MsPartyRegistryProxyRestClientTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/client/UserRegistryRestClientTest.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java
> hotfix: limit result post search users

- core/src/main/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImplTest.java
added check to institution onboarding before add users
Users cannot be onboarded if institution doesn't have product already onboarded
> Fix: added check to institution onboarding before add users

- app/src/main/resources/swagger/api-docs.json
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/onboarding/BillingDataDto.java
> [SELC-4755] Removing field mandatory for onboarding

- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardingData.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/institutions/InstitutionLocationDataDto.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/onboarding/OnboardingProductDto.java
> fix: Removing field mandatory for onboarding

- app/src/main/resources/swagger/api-docs.json
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerV2Test.java
Added v2 version of getInstitutionProductUsers that retrieve data from user-ms
> hotfix: added endpoint getInstitutionProductUsersV2

- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/InstitutionResourceMapper.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerV2Test.java
> hotfix: added institutions v2 filter ACTIVE and mapping status

- core/src/main/java/it/pagopa/selfcare/external_api/core/UserService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/UserServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerV2Test.java
getInstitutions v2 use a dedicated method on service getOnboardedInstitutionsDetailsActive that retrive only ACTIVE record
> hotfix: added institutions v2 filter ACTIVE

- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImplTest.java
> hotfix: getInstitutionUserProductsV2 filter personId

- core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java
> hotfix: getOnboardedInstitutionsDetailsActive set products only for product-id

- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/user/RelationshipState.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/UserServiceImplTest.java
Refactor getOnboardedInstitutionsDetails for setting correct product status 
POST /users return wrong productInfo status
> [SELC-4849] refactor: getOnboardedInstitutionsDetails for setting correct product status

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/ProductInfo.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/UserServiceImplTest.java
Added product role to POST users response
This information could be useful for support
> [SELC-4849] feat: added product role to POST users response

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/MsCoreConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/client/MsCoreRestClient.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/PartyConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionController.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerTest.java
…rom implementation classes
Removed unused API's from InstitutionController and related methods
Since the introduction of ms-user some of the api's has been implemented on a new version of institutionController, hence the ones in the previoous one were not used anymore. This task has been created to clean up the code from unnecessary code and for maintainability
no test required
> [SELC-4869] feat: Removed unused API's from InstitutionController

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/Billing.java
- connector/rest/docs/openapi/api-selfcare-onboarding-docs.json
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/institutions/InstitutionResource.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/InstitutionResourceMapper.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/OnboardingMapper.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/onboarding/BillingDataDto.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/resources/expectations/InstitutionResourceV2_1element.json
- web/src/test/resources/expectations/InstitutionResourceV2_2elements.json
- web/src/test/resources/expectations/OnboardedInstitutionInfo.json
Added taxCodeInvoicing to:
• Billing
• InstitutionResource
• BillingDataDto
The addition of this new field is necessary as someUO have a taxCode different from that of the central body, which they use for invoicing, called SFE taxCode.
The microservice has been started locally and it has been verified that it is present in the Request
> [SELC - 4788] feat: added taxCodeInvoicing to api V2

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/MsPartyRegistryProxyConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/nationalRegistries/LegalVerification.java
- connector/rest/docs/openapi/api-selfcare-registry-proxy-docs.json
- connector/rest/pom.xml
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/MsPartyRegistryProxyConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/client/MsRegistryProxyNationalRegistryRestClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/config/MsRegistryProxyNationalRegistriesClientConfig.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/RegistryProxyMapper.java
- connector/rest/src/main/resources/config/ms-party-registry-proxy-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/MsPartyRegistryProxyConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/client/MsPartyRegistryProxyRestClientTest.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java
- pom.xml
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/NationalRegistryController.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/NationalRegistryMapper.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/national_registries/LegalVerificationResource.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/national_registries/VerifyRequestDto.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/NationalRegistriesControllerTest.java
- web/src/test/resources/expectations/LegalVerify.json
Add new api for Verifying if given taxId is legal of given institution identified with vatNumber
PNPG needs this api for providing support to users
> [SELC-4988] feat: Add new api to call national-registries for verifying Legals for pnpg

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionController.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerV2Test.java
* New Endpoint: Added /institutions/{institutionId}/users to manage users at the institution level.
* Deprecated Endpoint: Marked /institutions/{institutionId}/products/{productId}/users as deprecated.
* API Documentation: Updated the OpenAPI specifications to reflect the new endpoint and deprecate the old one.
introduces a new endpoint **/institutions/{institutionId}/users** and deprecates the existing endpoint **/institutions/{institutionId}/products/{productId}/users**. The new endpoint will be used in the external API for automatic OpenAPI generation.
> [SELC-5047] feat: Add New Endpoint /institutions/{institutionId}/users

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/NationalRegistryController.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/UserV2Controller.java
- added support-pnpg and NationalRegistry to verifyLegal API
- added support-pnpg to getUserInfo API
- aligned openapi
Align tags for implementation of this [RFC](https://pagopa.atlassian.net/wiki/spaces/SCP/pages/edit-v2/1084883169)
> [SELC-5094] chore: added support-pnpg and NationalRegistry tags

- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/InstitutionMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImplTest.java
- Fixed InstitutionMapper for null billing
When billing in institution's onboarding billing is null application thows nullpointerException
> [SELC-5086] Fix: InstitutionMapper for null billing

- infra/apim_v2/env/prod/terraform.tfvars
Changed production snet CIDR colliding with another one
The CIDR set for the stv2 APIM collides with an existing snet in production. This does not happen in dev and uat environment.
> Changed subnet cidr colliding in production

- infra/apim_v2/apim.tf
- infra/apim_v2/data.tf
> Added pnpg kv permissions

- infra/apim_v2/data.tf
- infra/apim_v2/jwt.tf
> Added pnpg certificate to v2 apims

- infra/apim_v2/api/ms_external_api/v2/open-api.yml.tpl
- infra/apim_v2/api/selfcare_support_service/v1/open-api.yml.tpl
- infra/apim_v2/apim.tf
- infra/apim_v2/apim_pnpg.tf
- infra/apim_v2/data.tf
- infra/apim_v2/env/dev/terraform.tfvars
- infra/apim_v2/env/prod/terraform.tfvars
- infra/apim_v2/env/uat/terraform.tfvars
- infra/apim_v2/variables.tf
Added these PR merged into selfcare-infra to update new apim instance:
* https://github.com/pagopa/selfcare-infra/pull/703
* https://github.com/pagopa/selfcare-infra/pull/700
* https://github.com/pagopa/selfcare-infra/pull/698
* https://github.com/pagopa/selfcare-infra/pull/699
Fix reference jwt and certificate for apim_pnpg
[SELC-5088]: https://pagopa.atlassian.net/browse/SELC-5088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5053]: https://pagopa.atlassian.net/browse/SELC-5053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update apim infra with SELC-5032, SELC-5033, SELC-5088

- infra/apim_v2/apim.tf
- infra/apim_v2/apim_pnpg.tf
- infra/apim_v2/data.tf
- infra/apim_v2/developer.tf
- infra/apim_v2/env/dev/developer/external/v1/index.html
- infra/apim_v2/env/dev/developer/external/v2/index.html
- infra/apim_v2/env/prod/developer/external/v1/index.html
- infra/apim_v2/env/prod/developer/external/v2/index.html
- infra/apim_v2/env/uat/developer/external/v1/index.html
- infra/apim_v2/env/uat/developer/external/v2/index.html
> [EC-233] - Prepare code for APIM v1 deletion

- infra/apim_v2/api/selfcare_support_service/v1/open-api.yml.tpl
updated count notifications api path to be more respectful of rest standards
dev APIM
> [SELC-5124] fix: updated count notifications api path to be more respectful of rest standards

- infra/apim_v2/env/dev/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
> chore: Move to Container App Env workload DEV

- infra/apim_v2/env/uat/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
> chore: Move to Container App Env workload UAT

- infra/apim_v2/api/ms_external_api/v2/jwt_auth_op_policy_user_group.xml.tpl
- infra/apim_v2/api/ms_external_api/v2/openapi.dev.json
- infra/apim_v2/api/ms_external_api/v2/openapi.prod.json
- infra/apim_v2/api/ms_external_api/v2/openapi.uat.json
- infra/apim_v2/api/selfcare_support_service/v1/jwt_auth_op_policy_user_group.xml.tpl
- infra/apim_v2/api/selfcare_support_service/v1/openapi.dev.json
- infra/apim_v2/api/selfcare_support_service/v1/openapi.prod.json
- infra/apim_v2/api/selfcare_support_service/v1/openapi.uat.json
- infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/jwt_auth_op_policy_user_group.xml.tpl
- infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/openapi.dev.json
- infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/openapi.prod.json
- infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/openapi.uat.json
- infra/apim_v2/api_pnpg/pnpg_support_service/v1/jwt_auth_op_policy_user_group.xml.tpl
- infra/apim_v2/api_pnpg/pnpg_support_service/v1/openapi.dev.json
- infra/apim_v2/api_pnpg/pnpg_support_service/v1/openapi.prod.json
- infra/apim_v2/api_pnpg/pnpg_support_service/v1/openapi.uat.json
- infra/apim_v2/apim.tf
- infra/apim_v2/apim_pnpg.tf
- change endpoint getUserGroupsUsingGET from "/user-groups/v1" to "v1/user-groups"
- remove url rewrite
- align openapi
This change is required to point to new versions APIs.
> [SELC-5099] feat: change endpoint getUserGroupsUsingGET from "/user-groups/v1" to "v1/user-groups"

- connector-api/pom.xml
- connector-api/src/main/java/it/pagopa/selfcare/external_api/api/MsCoreConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardedInstitutionResource.java
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/mapper/OnboardingInstitutionMapper.java
- connector/rest/pom.xml
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/InstitutionMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/InstitutionMapperTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/UserMsConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/UserService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/UserServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/InstitutionResourceMapper.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerV2Test.java
- web/src/test/resources/expectations/InstitutionResourceV2_1element.json
- web/src/test/resources/expectations/InstitutionResourceV2_2elements.json
- web/src/test/resources/expectations/OnboardedInstitutionInfo.json
- Refactor API /v2/institutions
The API was very complex from an implementation perspective and therefore needed to be simplified.
> [SELC-5244] Feat: Refactor API /v2/institutions

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/external_api/model/user/UserProductResponse.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java
- core/src/test/resources/expectations/UserInfoV2.json
- core/src/test/resources/expectations/UserInfoWithoutTaxCode.json
- core/src/test/resources/expectations/UserInstitutionV2.json
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java
- web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/UserInfoResourceMapper.java
- web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerV2Test.java
- web/src/test/resources/expectations/UserInfo.json
- web/src/test/resources/expectations/UserResource.json
-  Refactor API /institutions/{institutionId}/users
-  Refactor API /institutions/{institutionId}/products/{productId}/users
The APIs was very complex from an implementation perspective and therefore needed to be simplified.
> [SELC-5243] Refactor APIs to retrieve UserData with role and productRoles

- infra/apim_v2/env/prod/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
> chore: Move to Container App Env workload PROD

- infra/apim_v2/api/ms_external_api/v2/getUserInstitutionUsingGet_op_policy.xml.tpl
- infra/apim_v2/api/ms_external_api/v2/openapi.dev.json
- infra/apim_v2/api/ms_external_api/v2/openapi.prod.json
- infra/apim_v2/api/ms_external_api/v2/openapi.uat.json
- infra/apim_v2/apim.tf
- add logo field in getUserInstitutionUsingGet policy
- set LOGO_URL variable in getUserInstitutionUsingGet apim
It was tested by applying this change in both dev and uat environments and called getUserInstitution API.
> [SELC-5379] feat: add logo url in getUserInstitutionUsingGet

- app/src/main/resources/swagger/api-docs.json
- infra/apim_v2/api/selfcare_support_service/v1/openapi_merge/openapi_merge.json
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/OnboardingV2Controller.java
* Added Onboarding Functions openapi inside support openapi-merge
* Added Responses annotation on /users to document better which responses return the endpoint
Support API also include some Onboarding Functions endpoint so the openapi merge file need to contain its openapi
> docs: added Onboarding Functions openapi on Support API

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/NationalRegistryController.java
response alignment for merge openapi
> ops: Added swagger annotation Responses to National Registry

- infra/apim_v2/api/ms_external_api/v2/getInstitution_op_policy.xml.tpl
- infra/apim_v2/api/ms_internal_api/v1/getInstitution_op_policy.xml.tpl
- infra/apim_v2/api_pnpg/external_api_data_vault/v1/getInstitution_op_policy.xml.tpl
- infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/getInstitution_op_policy.xml.tpl
Remove outbound where logo were added as static endpoint
This logic issue error after we have introduced logo field on getInstitution endpoint. Adding logo using policies could cause misconfiguration.
> hotfix: Remove Adding logo on Outbound Policy

- infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/openapi.dev.json
- infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/openapi.prod.json
- infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/openapi.uat.json
- infra/apim_v2/apim_pnpg.tf
-  set getInstitutionsUsingGET operationId to getInstitutionsUsingGETOld in pnpg external apim
> [SELC-5431] fix: align getInstitutions operationId for pnpg external

- infra/apim_v2/apim_pnpg.tf
Modify the following operation ids in apim_pnpg.tf file:
- getInstitution -> retrieveInstitutionByIdUsingGET
- getInstitutionProductUsersUsingGET -> getInstitutionUsersByProductUsingGET
- getInstitutionUserProductsUsingGET -> getInstitutionProductsUsingGET
It was tested by applying in dev environment and calling the corresponding APIs.
> [SELC-5463] feat: align external-v2 pnpg operation Identifiers

- infra/apim_v2/api/jwt_auth_op_policy_user_group.xml
- add productId filter in jwt_auth_op_policy_user_group.xml
> [SELC-5431] fix: add productId filter in jwt_auth_op_policy_user_group.xml

- .github/workflows/apim_infra_release.yml
- .github/workflows/call_update_docs_and_notification.yml
- infra/apim_v2/env/dev/developer/support/v1/index.html
- infra/apim_v2/env/prod/developer/support/v1/index.html
- infra/apim_v2/env/uat/developer/support/v1/index.html
* Added Documentation for Support API in the Developer Portal:
Detailed documentation has been added for the Support API within our Developer Portal.
This includes comprehensive guides, API reference, use cases, and examples to assist developers in integrating and utilizing the Support API effectively.
* Enabled Slack Notifications for API Changes:
Implemented a notification system to alert relevant teams via Slack whenever changes occur in the Support API.
This ensures that any modifications, updates, or potential issues are communicated promptly to the stakeholders, improving awareness and coordination across teams.
> chore: Documentation for Support API and Slack Notifications 

- .github/workflows/apim_infra_release.yml
- infra/apim_v2/developer.tf
- infra/apim_v2/env/dev/developer/internal/v1/index.html
**Added Documentation for Internal API in the Developer Portal:**
Detailed documentation has been added for the Internal API within our Developer Portal.
This includes comprehensive guides, API reference, use cases, and examples to assist developers in integrating and utilizing the Internal API effectively.
**Enabled Slack Notifications for API Changes:**
Implemented a notification system to alert relevant teams via Slack whenever changes occur in the Internal API.
This ensures that any modifications, updates, or potential issues are communicated promptly to the stakeholders, improving awareness and coordination across teams.
> chore: Documentation for Internal API and Slack Notifications

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/external_api/web/controller/UserV2Controller.java
> [SELC-5398] feat: Added tag external-pnpg to getUserInstitution API

- connector-api/pom.xml
- connector/rest/pom.xml
- connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/ProductConnectorImplTest.java
Increase sdk product version 0.2.0
> [SELC-5520] feat: increase sdk product version to handle institutionContractMapping issue

- .github/workflows/call_openapi_merge.yml
- .github/workflows/create_openapi_merge.yml
- .github/workflows/create_openapi_merge_dev.yml
* Add statement scheduler on Github Action
* Add configuration for prod,uat and dev environment
This PR adds a schedule to trigger the Create OpenAPI action, the schedule ensures that all open-api files are updated. At the moment, external-api will be skipped.
> ops: Setup scheduler for Create-Merge OpenAPI action

- .github/workflows/create_openapi_merge.yml
- infra/apim_v2/apim_pnpg.tf
* Add OperationId to apim_pnpg
* fix cron expression UAT and PROD
OperationId is mandatory when we want to forward the request to a certain microservice, in this case user-ms
> [SELC-5572] feat: Add OperationId getUserInfoUsingGET to support-pnpg API

- .github/workflows/apim_infra_release.yml
- .github/workflows/call_update_docs_and_notification.yml
- infra/apim_v2/data.tf
- infra/apim_v2/developer.tf
- infra/apim_v2/env/dev/developer/support-pnpg/v1/index.html
- infra/apim_v2/env/prod/developer/support-pnpg/v1/index.html
- infra/apim_v2/env/uat/developer/support-pnpg/v1/index.html
* Add folders to azure storage which contains index.html and openapi.json
* Add boolean flag "is_pnpg" on infra release pipeline to value appropriate suffix for pnpg resources 
* Add step to release OpenAPI Support PNPG on infra release pipeline
This PR permits to expose OpenAPI documentation about Support PNPG API at https://pnpg.selfcare.pagopa.it/developer/support-pnpg/v1/index.html
> [SELC-5568] feat: Support PNPG API Documentation

- .github/workflows/call_update_docs_and_notification.yml
> fix: Remove - from pnpg_suffix on Update Docs and Notification Release

- app/pom.xml
> [SELC-5696] feat: updated SDK version

- app/pom.xml
- app/src/main/resources/swagger/api-docs.json
- app/src/test/resources/expectations/Product.json
- app/src/test/resources/expectations/ProductResource.json
- app/src/test/resources/expectations/ProductResources.json
> [SELC-5696] feat: updated unit test

- .github/workflows/pr_ms.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_ms_pnpg.yml
- .github/workflows/release_open_api.yml
> chore: change trigger paths on pipeline with src/**

- infra/apim_v2/apim_pnpg.tf
fix: added policy for new apis on party-registry in pnpg-support group
> fix: added policy for new apis on party-registry in pnpg-support group

- src/main/docs/openapi/api-selfcare-onboarding-docs.json
- src/main/java/it/pagopa/selfcare/external_api/service/ContractServiceImpl.java
- src/main/java/it/pagopa/selfcare/external_api/service/OnboardingServiceImpl.java
- src/main/java/it/pagopa/selfcare/external_api/service/TokenServiceImpl.java
- src/test/java/it/pagopa/selfcare/external_api/service/ContractServiceImplTest.java
- src/test/java/it/pagopa/selfcare/external_api/service/TokenServiceImplTest.java
updated onboarding ms openapi and api naming
It was not possible to onboard an institution with PDND_INFOCAMERE as origin
> [SELC-5718] fix: updated onboarding ms openapi and api naming

- src/main/docs/openapi/api-selfcare-onboarding-docs.json
- src/main/java/it/pagopa/selfcare/external_api/service/ContractServiceImpl.java
- src/main/java/it/pagopa/selfcare/external_api/service/OnboardingServiceImpl.java
- src/main/java/it/pagopa/selfcare/external_api/service/TokenServiceImpl.java
- src/test/java/it/pagopa/selfcare/external_api/service/ContractServiceImplTest.java
- src/test/java/it/pagopa/selfcare/external_api/service/TokenServiceImplTest.java
> [SELC - 5718] fix: updated onboarding ms openapi and api naming

- .github/workflows/pr_detect_openapi_billing_portal.yml
- infra/apim_v2/api/billing-portal-api/v1/openapi_merge/openapi_merge.json
- infra/apim_v2/api/billing-portal-api/v1/openapi_merge/openapi_template.json
Adding new configuration file for generate new api
Adding new api for billing portal, enabling updated recipient code
> [SELC-5769] feat: Added open api generator for billing portal

- .github/workflows/call_openapi_merge.yml
> [SELC-5769] Fix update call action

- .github/workflows/apim_infra_release.yml
- .github/workflows/call_openapi_merge.yml
- .github/workflows/create_openapi_merge.yml
> [SELC-5769] Fix update call action 

- .github/workflows/apim_infra_release.yml
- .github/workflows/call_openapi_merge.yml
- infra/apim_v2/api/billing-portal-api/v1/openapi_merge/openapi_merge.json
> [SELC-5769] Update actions

- infra/apim_v2/api/base_ms_url_external_policy.xml.tpl
Change APIM policy condition using product.id instead of variable
> [SELC-5775] Fix policy condition

- infra/apim_v2/api/base_ms_url_external_policy.xml.tpl
- infra/apim_v2/apim.tf
- infra/apim_v2/apim_pnpg.tf
- infra/apim_v2/developer.tf
- infra/apim_v2/env/prod/terraform.tfvars
- infra/container_apps/README.md
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/github-runner/variables.tf
> [SELC-5775] Running pre-commit

- infra/apim_v2/apim.tf
Added new module and resource for billing portal into Apim
> [SELC-5769] feat: Added new module for billing portal into Apim

- infra/apim_v2/api/billing-portal-api/v1/openapi_merge/openapi_merge.json
Added new config for billing-portal
> [SELC-5769] feat: Updated openapi for billing-portal (onboarding-backend)

- infra/apim_v2/api/base_policy_config.xml.tpl
- infra/apim_v2/apim.tf
Added new custom file of policy and updated apim config with new endpoint
> [SELC-5769] feat: Added new policy and updated apim config

- infra/apim_v2/apim.tf
Updated base path of billing-portal config
> [SELC-5769] feat: Updated base path of billing-portal config

- pom.xml
- src/main/java/it/pagopa/selfcare/external_api/mapper/UserMapper.java
- src/main/resources/swagger/api-docs.json
- src/test/java/it/pagopa/selfcare/external_api/controller/BaseControllerTest.java
- src/test/java/it/pagopa/selfcare/external_api/controller/InstitutionControllerV2Test.java
- src/test/resources/expectations/Product.json
- src/test/resources/expectations/ProductResources.json
- src/test/resources/expectations/TokensResource.json
- src/test/resources/expectations/UserInfoResource.json
Change mapping ProductRoleLabel with product.productLabel on GET /v2/users
productLabel present on product configuration Indicates a custom description of product role in exceptional case such as prod-pagopa.
> [SELC-5861] feat: mapping ProductRoleLabel with product.productLabel on GET /v2/users

- src/main/docs/openapi/api-selfcare-user-docs.json
- src/main/java/it/pagopa/selfcare/external_api/client/MsUserApiRestClient.java
- src/main/java/it/pagopa/selfcare/external_api/mapper/UserMapper.java
- src/main/java/it/pagopa/selfcare/external_api/service/InstitutionServiceImpl.java
- src/main/java/it/pagopa/selfcare/external_api/service/OnboardingServiceImpl.java
- src/main/java/it/pagopa/selfcare/external_api/service/UserServiceImpl.java
- src/test/java/it/pagopa/selfcare/external_api/service/InstitutionServiceImplTest.java
- src/test/java/it/pagopa/selfcare/external_api/service/OnboardingServiceImplTest.java
- src/test/java/it/pagopa/selfcare/external_api/service/UserServiceImplTest.java
Update user-ms openapi.json and its class reference
Added ADMIN_EA has caused a breaking change
> [SELC-5862] fix: ADMIN_EA is not parsed with previous openapi of user-ms

- infra/apim_v2/api_pnpg/internal_api_for_pnpg/v1/openapi.dev.json
- infra/apim_v2/api_pnpg/internal_api_for_pnpg/v1/openapi.prod.json
- infra/apim_v2/api_pnpg/internal_api_for_pnpg/v1/openapi.uat.json
- infra/apim_v2/api_pnpg/internal_api_for_pnpg/v1/openapi_merge/openapi_merge.json
- infra/apim_v2/api_pnpg/internal_api_for_pnpg/v1/openapi_merge/openapi_template.json
- infra/apim_v2/apim_pnpg.tf
Added new empty api group for internal api pnpg
> [PNPG-236] feat: added new group for internal api pnpg

- infra/apim_v2/api/ms_external_api/v2/openapi_merge/openapi_merge.json
- infra/apim_v2/apim.tf
On external v2 we need to add also openapi from onboarding function
> [SELC-5849] Add selfcare-onboarding-functions for merge openapi external-v2

- .github/workflows/call_openapi_merge.yml
- .github/workflows/create_openapi_merge.yml
- .github/workflows/pr_detect_openapi_pnpg_internal.yml
updated github actions to handle new internal-pnpg api group
> [PNPG-236] feat: updated github actions to handle new internal-pnpg api group

- infra/apim_v2/api/ms_external_api/v2/openapi.dev.json
- infra/apim_v2/api/ms_external_api/v2/openapi.uat.json
> [SELC-5851] Update openapi restoring messageAcknowledgment API

- infra/apim_v2/env/dev/developer/billing-portal/v1/index.html
- infra/apim_v2/env/prod/developer/billing-portal/v1/index.html
- infra/apim_v2/env/uat/developer/billing-portal/v1/index.html
Adding configuration for create developer portal for billing-portal
> Update developer portal for billing-portal

- infra/apim_v2/apim_pnpg.tf
> Create apim for internal pnpg

- infra/apim_v2/apim_pnpg.tf
fix path of microservices in pnpg-internal api
> [PNPG-236] fix: path of microservices in pnpg-internal api

- infra/apim_v2/api/api_key_fn_op_policy_message.xml.tpl
- infra/apim_v2/api/ms_external_api/v2/openapi.dev.json
- infra/apim_v2/api/ms_external_api/v2/openapi.prod.json
- infra/apim_v2/api/ms_external_api/v2/openapi.uat.json
- infra/apim_v2/apim.tf
Update pipeline for fn messageAcknowledge api
> fix: Add new url for messageAcknowledge

- src/main/docs/openapi/api-selfcare-onboarding-docs.json
- src/main/java/it/pagopa/selfcare/external_api/controller/OnboardingV2Controller.java
- src/main/java/it/pagopa/selfcare/external_api/mapper/OnboardingMapper.java
- src/main/java/it/pagopa/selfcare/external_api/mapper/OnboardingResourceMapper.java
- src/main/java/it/pagopa/selfcare/external_api/service/OnboardingService.java
- src/main/java/it/pagopa/selfcare/external_api/service/OnboardingServiceImpl.java
- src/main/resources/swagger/api-docs.json
- src/main/resources/swagger/swagger_en.properties
- src/test/java/it/pagopa/selfcare/external_api/controller/OnboardingV2ControllerTest.java
- src/test/java/it/pagopa/selfcare/external_api/service/OnboardingServiceImplTest.java
- added new API for PSPs Import
The implementation of this API is necessary as it is used for the import of PSPs already contracted
the microservice was started locally and the API was invoked with an example request. in the first case it returned 400 because the request was wrong, in the second case it returned 201 and onboarding was completed correctly.
> [SELC-5803] feat: added new API for PSPs Import

- infra/apim_v2/apim.tf
- added policy for onboardingImportUsingPOST
API invocation from azure apim
> [SELC-5813] fix: added policy for onboardingImportUsingPOST

- src/main/java/it/pagopa/selfcare/external_api/mapper/ProductsMapper.java
- src/test/java/it/pagopa/selfcare/external_api/service/InstitutionServiceImplTest.java
[Change of products configuration](https://github.com/pagopa/selfcare-onboarding/pull/561) has broken /products endpoint. This PR aims to resolve this issues.
> [SELC-5895] fix: refactor mapping contractTemplatePath and contractTemplateVersion

- src/main/java/it/pagopa/selfcare/external_api/mapper/ProductsMapper.java
Fix of this [PR](https://github.com/pagopa/selfcare-external-api-backend/pull/469)
> [SELC-5895] fix: retrieve mapping using getInstitutionContractTemplate

- src/main/java/it/pagopa/selfcare/external_api/mapper/ProductsMapper.java
- src/main/java/it/pagopa/selfcare/external_api/model/product/ProductResource.java
- src/main/resources/swagger/api-docs.json
- src/main/resources/swagger/swagger_en.properties
Remove @notBlack for contractTemplatePath
> Update resource mapper

- infra/apim_v2/developer.tf
Added terraform resource to upload billing-developer index-html. It need to expose swagger documentation.
> ops: Added upload resource billing developer index.html

- .github/workflows/create_release_branch.yml
- infra/apim_v2/openapi_merge/remove_v_and_tags.js
**Updated securitySchemes**:
* Removed the bearerAuth scheme and replaced it with apiKeyHeader.
* Defined apiKeyHeader with the property `Ocp-Apim-Subscription-Key`
**Updated security requirements**:
* Replaced bearerAuth references in the path operation security definitions with apiKeyHeader.
**CI/CD Workflow Enhancements:**
* Modified `.github/workflows/create_release_branch.yml` to trigger the following workflows automatically after a release branch is created
> ops: Update logic creation of OpenAPIs paths and security schemes

- .opex/api-selfcare-external-api/env/prod/config.yaml
> fix: added availability information

- infra/apim_v2/apim.tf
Renamed operation_id of getFilesFromPath
> [SELC-6156] feat: Fixed rules for getFilesFromPath

- pom.xml
- src/main/docs/openapi/api-selfcare-core-docs.json
- src/main/java/it/pagopa/selfcare/external_api/mapper/InstitutionMapperCustom.java
- src/main/java/it/pagopa/selfcare/external_api/model/institution/Institution.java
- src/main/java/it/pagopa/selfcare/external_api/model/institution/InstitutionResource.java
- src/main/java/it/pagopa/selfcare/external_api/model/institution/InstitutionType.java
- src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardedInstitutionResource.java
- src/main/java/it/pagopa/selfcare/external_api/model/onboarding/mapper/OnboardingInstitutionMapper.java
- src/main/java/it/pagopa/selfcare/external_api/service/OnboardingServiceImpl.java
- src/main/resources/swagger/api-docs.json
- src/test/java/it/pagopa/selfcare/external_api/service/OnboardingServiceImplTest.java
- update selfcare-commons version from 2.5.4 to 2.5.5
- update onboarding-sdk version to 0.6.2
- update ms-core swagger
- replace onboarding-sdk InstitutionType in getInstitutionsUsingGETDeprecated response with a new enum to avoid GPU
- align mappers
This change is required to manage GPU institution type and to avoid the introduction of breaking changes in getInstitutionsUsingGETDeprecated API
It was tested locally
> [SELC-6238] feat: manage GPU institutionType

- pom.xml
Updated sdk common version to 0.6.9
> feat: Updated common sdk version

- .github/workflows/call_release_infra.yml
- .github/workflows/release_integration_test_infra.yml
> Added new action for release integration test env to infra

- .github/workflows/integration_test.yml
Added checkout to read inputs value
> Fixed current env into job

- src/main/docs/openapi/api-selfcare-onboarding-docs.json
- src/main/java/it/pagopa/selfcare/external_api/service/TokenServiceImpl.java
- src/test/java/it/pagopa/selfcare/external_api/service/TokenServiceImplTest.java
> feat: updated api-selfcare-onboarding-docs.json

- .github/workflows/integration_test.yml
> [SELC] Pin actions/checkout action to 11bd719

- infra/apim_v2/api/pdnd_infocamere_api/v1/openapi.dev.json
- infra/apim_v2/api/pdnd_infocamere_api/v1/openapi.prod.json
- infra/apim_v2/api/pdnd_infocamere_api/v1/openapi.uat.json
- infra/apim_v2/api/pdnd_infocamere_api/v1/openapi_merge/openapi_merge.json
- infra/apim_v2/api/pdnd_infocamere_api/v1/openapi_merge/openapi_template.json
- infra/apim_v2/apim.tf
PDND Infocamera API available fom apim
> Adding API for PDND Interoperabilità

- infra/apim_v2/api/external_api_contract/v1/openapi_merge/openapi_merge.json
Adding new api messageAcknowledgment
The integration to external service Conservazione digitale a norma, should need an api for notify ingestion status
> [SELC-6715] Adding new api from fn

- infra/apim_v2/apim_pnpg.tf
Set correct operationId for institutionsByLegalTaxId and legalAddressUsingGET
> [SELC-6720] fix: set correct operationId

- infra/apim_v2/api/ms_internal_api/v1/openapi.dev.json
- infra/apim_v2/api/ms_internal_api/v1/openapi.prod.json
- infra/apim_v2/api/ms_internal_api/v1/openapi.uat.json
- infra/apim_v2/apim.tf
- Added API deleteOnboarding for all env: DEV, UAT and PROD
- Added policy for deleteOnboarding API
These changes are necessary to allow service management team to invoke the API DELETE /onboarding/{id}
> [SELC-6596] feat: added API deleteOnboarding for all env

- .github/workflows/apim_infra_release.yml
> Updated action cache version to v4

- .github/workflows/apim_infra_release.yml
- .github/workflows/call_deploy_openapi.yml
- .github/workflows/call_detect_openapi.yml
- .github/workflows/call_integration_test.yml
- .github/workflows/call_openapi_merge.yml
- .github/workflows/call_release_infra.yml
- .github/workflows/call_update_docs_and_notification.yml
- .github/workflows/create_release_branch.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_open_api.yml
update ubuntu from 20.04 to 24.04
version 20.04 will be deprecated soon
> feat: update ubuntu from 20.04 to 24.04

- src/main/docs/openapi/api-selfcare-onboarding-docs.json
> fix: Updated api-docs

- infra/apim_v2/api/ms_internal_api/v1/openapi.dev.json
- infra/apim_v2/api/ms_internal_api/v1/openapi.prod.json
- infra/apim_v2/api/ms_internal_api/v1/openapi.uat.json
> fix: Deleted node security from definition of api for dev-uat-prod (internal)

- infra/apim_v2/apim.tf
- infra/apim_v2/apim_pnpg.tf
Moved institutionPdndByTaxCodeUsingGET into the correct file definition
> fix: Moved definition of endpoint from apim into apim-pnpg

- infra/apim_v2/apim_pnpg.tf
Fixed declaration of policy for endpoint (pnpg)
> fix: Updated apim config for pnpg

- infra/apim_v2/api/external_api_contract/v1/openapi_merge/openapi_merge.json
Added path to onboarding-function into template
> Fixed template file to include group "conservazione" into onboarding-functions openapi

- infra/apim_v2/apim.tf
- infra/apim_v2/apim_pnpg.tf
> fix: removed deprecated api policy

- infra/apim_v2/api/jwt_base_policy.xml.tpl
- infra/apim_v2/api/ms_external_api/v2/getInstitutions_op_policy.xml.tpl
- infra/apim_v2/apim.tf
- infra/apim_v2/data.tf
> fix: updated policy for getInstitutions

- infra/apim_v2/apim.tf
> fix: updated ms backend url

- src/main/java/it/pagopa/selfcare/external_api/service/ContractServiceImpl.java
- src/test/java/it/pagopa/selfcare/external_api/service/ContractServiceImplTest.java
> [SELC-6884] Call token.getContract api for retrieve onboarding contract file

- src/main/java/it/pagopa/selfcare/external_api/mapper/OnboardingMapperCustom.java
- src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardingAggregatorImportDto.java
- src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardingImportDto.java
- src/main/resources/swagger/api-docs.json
- src/test/java/it/pagopa/selfcare/external_api/controller/OnboardingV2ControllerTest.java
Removed null constraint on OnboardingAggregatorImportDto and OnboardingImportDto
> [SELC-7023] feat: removed null constraint on OnboardingAggregatorImportDto and OnboardingImportDto

- src/main/docs/openapi/api-selfcare-onboarding-docs.json
- src/main/java/it/pagopa/selfcare/external_api/mapper/OnboardingMapper.java
- src/main/java/it/pagopa/selfcare/external_api/mapper/OnboardingMapperCustom.java
- src/test/java/it/pagopa/selfcare/external_api/mapper/OnboardingMapperTest.java
updated object data to send mail for import and import aggregator
the boolean has been set to send the completion email in the subject so that the sending of the email on the function side for the IO import is triggered
the api was called and it was verified that the email was sent correctly
> [SELC-7041] feat: updated object data to send mail for import and import aggregator

- infra/apim_v2/apim.tf
- Added v2 to getDelegationsUsingGET_2
Fix path
> [SELC-7169] Added v2 to getDelegationsUsingGET_2

- infra/apim_v2/api_product/registro-beni/policy.xml
- infra/apim_v2/apim.tf
- added prod-registro-beni to apim
it is a new product that must be integrated with SC therefore it was necessary to expose the product module on apim
> [SELC-7218] feat: added prod-registro-beni to apim

- infra/apim_v2/api/internal_user_api/v1/openapi.dev.json
- infra/apim_v2/api/internal_user_api/v1/openapi.prod.json
- infra/apim_v2/api/internal_user_api/v1/openapi.uat.json
> [#SELC-7067] Expose new Internal User API

- infra/apim_v2/apim.tf
- Added getDelegateInstitutions to apim external v2
- Added getDelegatorInstitutions to apim external v2
Expose APIs on external-v2
> [SELC-7265] Added getDelegateInstitutions and getDelegatorInstitutions to apim external v2

- src/main/docs/openapi/api-selfcare-onboarding-docs.json
- src/main/java/it/pagopa/selfcare/external_api/model/onboarding/InstitutionUpdate.java
Added atecoCodes as attribute for API getTokens
This new attribute is necessary for other consumers of this API and in particular for prod-idpay-merchant
I have deployed the feature branch in DEV and tested the **API /v1/tokens/products/{productId}**
> [SELC-7360] feat: added atecoCodes as attribute for API getTokens

- .github/workflows/call_integration_test_bruno.yml
- .github/workflows/integration_test_bruno.yml
- infra/integration-test/Selfcare-External-Integration-Environment.bru
- infra/integration-test/integration_test.tf
- integration-test/bruno/External/folder.bru
- integration-test/bruno/External/getContract.bru
- integration-test/bruno/External/getInstitutionProducts.bru
- integration-test/bruno/External/getInstitutionUsersByProduct.bru
- integration-test/bruno/UserV2/folder.bru
- integration-test/bruno/UserV2/getUserInfo.bru
- integration-test/bruno/bruno.json
- integration-test/bruno/collection.bru
- Created a bruno collection
- Created a dedicated bruno workflow
Evaluation of Bruno, as an open source alternative to postman and newman
- Local tests
> [SELC-7508] Bruno collection and workflow

- src/main/docs/openapi/api-selfcare-onboarding-docs.json
- src/main/java/it/pagopa/selfcare/external_api/mapper/TokenMapper.java
- src/main/java/it/pagopa/selfcare/external_api/model/institution/Payment.java
- src/main/java/it/pagopa/selfcare/external_api/model/onboarding/InstitutionUpdate.java
- src/main/resources/swagger/api-docs.json
Added attributes legalForm and payment into response for api v1/tokens
I have deployed the fature branch in DEV and tested the api GET v1/tokens verifying values for field legalForm and payment
> [SELC-7439] feat: added attributes legalForm and payment into response for api v1/tokens

- infra/apim_v2/apim.tf
- Added delete user group operations
Add operations so that APIM can found the new APIs
> [SELC-7672] Added operations to apim.tf

- infra/apim_v2/apim.tf
- Added getDelegationsUsingGET_2
- Added addMembersToUserGroupWithParentInstitutionIdUsingPUT
- Added createUserByUserId
APIs used by user-cdc
- Local tests
> [SELC-7705] Added new APIs to apim.tf (ms_internal)
