pagopa/selfcare-external-api-backend

CODEOWNERS, core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java, core/src/main/resources/config/core-config.properties, core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/external_api/core/config/CoreTestConfig.java, helm/values.yaml
Removed hard coded service type from InstitutionServiceImpl 
Needed to make serviceType configurable in order to retrieve Users FiscalCodes based on caller Id (X-selfcare-uid)
The microservice has been deployed on dev environment and the api has been tested for different service types
=> [SELC-2363] - Configurazione variabile d'ambiente per Service type

connector/rest/src/main/resources/config/party-process-rest-client.properties
set REST_CLIENT_READ_TIMEOUT to 30 sec
set REST_CLIENT_CONNECT_TIMEOUT to 30 sec
Onboarding request takes a long time, increasing timeout is a temporany solution before moving to async handling
=> fix: remove duplicated connection timeout

connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardingDataMapper.java
Added empty list of geographic taxonomies before calling completeOnboarding
geographic taxonomies list required to procede with onboarding
Local environment
=> add empty collection for geographicTaxonomy SELC-3289

connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardingDataMapper.java, connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/PdaOnboardingData.java, core/src/main/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImpl.java
Added contractPath in onboarding/pda API
contractPath and contractVersion are required fields to complete onboarding on ms-core API
local environment
=> SELC-3289 Added contractPath to /onboarding/pda API 

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/ProductInfo.java, core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java
Added userStatus into productInfo node for getUserInfo API
This change was requested from support service in order to have info about status for onboarded product linked to an user
I have run ms-core and external-api-backend microservices and tested the api getUserInfo
=> [SELC-3214] feat: added userStatus into productInfo node for getUserInfo

core/src/main/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImpl.java
Added institution description to request body of onboarding/complete API
We need to get the description of the institution created with the api /institution/from-pda and set it in the request body of the call to onboarding/complete. Because the description we get from the from-pda call might be different than what we provided as input, if the institution is created from IPA.
=> Fix: retrieve Institution description from ms-core before calling onboarding/complete API

.github/workflows/release_open_api.yml
Added openapi-diff step into Github action to detect breaking changes.
In order to detect incompatible changes between the branch of release-dev and the branch of any new developmen, it has been added into githib action a step that check differences between the two open api. In particular:
- The step will cause the failure of github action in case of deletion of attribute from resources
- The step will cause the failure of github action in case of renaming of attribute from resources
- No failure in case of new attribute added in resources
=> [SELC-3416] feat: added github action to detect breaking changes into open api

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/UserController.java
Added new tag **external-v2** for operation that will be include into open-api for APIM
In order to avoid manual construction of open-api for APIM, all operations that will be included into this document are tagged with **external-v2** or **support**. In this way, a step of github action will scan them and automatically include into open-api.
=> [SELC-3460] feat: added tag external-v2 for automatic generation of open-api

connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardingImportContract.java, web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/OnboardingMapper.java
- added new activadetAt information in OnboardingImportContract Object
This addition was necessary because the oldOnboardingContract and autoApproval APIs invoke the API present on the core microservice to complete onboarding
the application was started locally, together with the core microservice and the APIs described above were subsequently invoked. We then verified that the activatedAt field was stored in the Token Entity
=> [SELC - 3708] feat: added activatedAd in OnboardingImportContract

app/src/main/resources/swagger/api-docs.json, helm/pnpg/values-dev.yaml, helm/pnpg/values-prod.yaml, helm/pnpg/values-uat.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/OnboardingController.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/PnPgController.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/ProductController.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/UserController.java, web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerTest.java, web/src/test/java/it/pagopa/selfcare/external_api/web/controller/OnboardingControllerTest.java, web/src/test/java/it/pagopa/selfcare/external_api/web/controller/PnPgControllerTest.java, web/src/test/java/it/pagopa/selfcare/external_api/web/controller/ProductControllerTest.java, web/src/test/java/it/pagopa/selfcare/external_api/web/controller/UserControllerTest.java
Remove /v1 prefix at helm file
Added /v1 prefix to web controller
/v1 prefix at helm value does not permit to add a new version of the endpoint, for example /v2/onboarding. Moving the prefix to controller enable possibility to create a new version of web controllers.
=> [SELC-4032] ops: move /v1 from helm to controller

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardingData.java, connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/OnboardingMapper.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/OnboardingController.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/OnboardingV2Controller.java, web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/OnboardingMapper.java, web/src/test/java/it/pagopa/selfcare/external_api/web/controller/OnboardingV2ControllerTest.java, web/src/test/java/it/pagopa/selfcare/external_api/web/model/mapper/OnboardingMapperTest.java
Added a new endpoint, version v2 GET **/onboarding/{externalId}**, which is designed to process onboarding. This endpoint triggers the new onboarding service
The existing onboarding process redirects to old onboarding service.
=> [SELC-4033] feat: added v2 for oldContractOnboarding

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/external_api/web/model/tokens/TokenResource.java
Update field status in TokenResource
In order to avoid conflicts with enum ReationshipState, the field status is changed into String. In this way is possible to manage new statuses such as COMPLETED
=> [SELC-4086] fix: Update field status in TokenResource

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/external_api/api/OnboardingMsConnector.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/OnboardingMsConnectorImpl.java, connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/mapper/OnboardingMapper.java, connector/rest/src/main/resources/config/ms-onboarding-rest-client.properties, connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/OnboardingMsConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/external_api/core/OnboardingService.java, core/src/main/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/external_api/core/OnboardingServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/OnboardingV2Controller.java, web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/OnboardingMapper.java, web/src/test/java/it/pagopa/selfcare/external_api/web/controller/OnboardingV2ControllerTest.java
Added a new endpoint, version v2 GET /onboarding/{externalId}, which is designed to process onboarding. This endpoint triggers the new onboarding service
The existing onboarding process redirects to old onboarding service.
I have run both microservices - onboarding and external-api - locally and tested the api for oldContractOnboarding
=> [SELC-4033] fix: Update oldContractOnboarding to invoke new onboading-ms

connector-api/src/main/java/it/pagopa/selfcare/external_api/model/user/UserInstitution.java, core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java
Fix v2 version of getInstitutionProductUsers that retrieve data from user-ms for permitting userId filter is null
=> hotfix: endpoint getInstitutionProductUsersV2 when user is null

core/src/main/java/it/pagopa/selfcare/external_api/core/ContractServiceImpl.java, core/src/test/java/it/pagopa/selfcare/external_api/core/ContractServiceImplTest.java
Added check on get contract when contractSigned is empty
contractSigned could be empty and some errors 500 occur
=> [SELC-4842] fix: if signed empty throw resource not found

connector-api/src/main/java/it/pagopa/selfcare/external_api/exceptions/InvalidRequestException.java, connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/decoder/FeignErrorDecoder.java, connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/decoder/FeignErrorDecoderTest.java, web/src/main/java/it/pagopa/selfcare/external_api/web/handler/ExternalApiExceptionHandler.java, web/src/test/java/it/pagopa/selfcare/external_api/web/handler/ExternalApiExceptionHandlerTest.java
Added in feign decoder the handling of http 400 response to throw appropriate exception
Before the intervention, API responses with http 400 status were not handled so the microservice always responded with http 500 status
local env
=> [SELC-4321] feat: handled http 400 status responses in feign decoder

app/src/main/resources/swagger/api-docs.json, core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java, web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerV2Test.java
* Modified the controller handling the /institutions/{institutionId}/products endpoint to accept the userId as a query parameter.
* Updated the logic to use the userId from the request parameter instead of extracting it from the JWT token.
This PR adds a userId request parameter to the /institutions/{institutionId}/products endpoint. This change allows the userId to be passed directly in the request rather than being retrieved from the JWT token.
=> [SELC-5047] feat: Add userId Request Parameter to /institutions/{institutionId}/products Endpoint

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/external_api/api/UserMsConnector.java, connector-api/src/main/java/it/pagopa/selfcare/external_api/model/user/UserInstitution.java, connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/UserMsConnectorImpl.java, connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/UserMsConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/external_api/core/UserService.java, core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/TokenController.java, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/UserV2Controller.java, web/src/main/java/it/pagopa/selfcare/external_api/web/model/mapper/UserInfoResourceMapper.java, web/src/main/java/it/pagopa/selfcare/external_api/web/model/user/UserInstitutionResource.java, web/src/test/java/it/pagopa/selfcare/external_api/web/controller/UserControllerV2Test.java
* Added a new GET /users endpoint to our service.
* The endpoint fetches user data from the ms-user microservice.
* Filtered out the userMailUuid attribute from the response to ensure it is not exposed externally.
This pull request introduces a new endpoint **GET /users** in our service, which mirrors the existing endpoint on the ms-user microservice. The primary purpose of this addition is to prevent the exposure of the _userMailUuid_ attribute, which is not significant or necessary for external use in the Selfcare product.
=> [SELC-5050] feat: Addition of GET /users Endpoint

connector-api/src/main/java/it/pagopa/selfcare/external_api/api/MsCoreConnector.java, connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImpl.java, connector/rest/src/test/java/it/pagopa/selfcare/external_api/connector/rest/MsCoreConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/external_api/core/InstitutionServiceImplTest.java
- Changed AddInstitution API to invoke _createPgInstitutionUsingPOST of ms-core
To prevent errors in the event of parallel institution creation requests, it is necessary to modify the flow in order to call a single API that retrieves or saves the institution via the taxCode
=> [SELC-5021] Fix: Change AddInstitution API to invoke _createPgInstitutionUsingPOST of ms-core

core/src/main/java/it/pagopa/selfcare/external_api/core/UserServiceImpl.java
- refactor getOnboardedInstitutionsDetails API to call user-ms api with 350 as pagesize (temporary fix)
we need to set pageSize in user-ms api call instead of use default (100) because some users have more than 100 items
=> [SELC-5086] Fix: refactor getOnboardedInstitutionsDetails API to call user-ms api with 350 as pagesize

infra/apim_v2/api/ms_external_api/v2/openapi_merge/openapi_merge.json, infra/apim_v2/api/ms_internal_api/v1/openapi_merge/openapi_merge.json, infra/apim_v2/api/selfcare_support_service/v1/openapi_merge/openapi_merge.json, infra/apim_v2/api_pnpg/external_api_for_pnpg/v2/openapi_merge/openapi_merge.json, infra/apim_v2/api_pnpg/pnpg_support_service/v1/openapi_merge/openapi_merge.json, infra/apim_v2/openapi_merge/remove_v_and_tags.js
This pull request introduces a modification to handle an issue when merging with OpenAPI specifications generated via Quarkus happens. Specifically, the generated OpenAPI includes an empty security schema, which needs to be replaced with a bearerAuth global.
This update addresses an issue where the OpenAPI specification generated by Quarkus includes an empty SecurityScheme, which is not valid for API security. By replacing this with a bearerAuth scheme, the OpenAPI spec will correctly define security requirements for the endpoints.
=> feat: Set bearerAuth global when SecurityScheme is empty

infra/apim_v2/api_pnpg/jwt_base_policy.xml.tpl, infra/apim_v2/apim_pnpg.tf
external-data vault API was using Selc certificare instead of PNPG
=> fix: reference pnpg certificate on external-data vault API

app/src/main/resources/swagger/api-docs.json, infra/apim_v2/apim.tf, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java, web/src/test/java/it/pagopa/selfcare/external_api/web/controller/InstitutionControllerV2Test.java
- make productId param optional in getContract and getInstitutionUsersByProduct
- rename userId param to userIdForAuth in getInstitutionUsersByProduct
- remove "external-v2" tag from getInstitutions
- remove unused operationIds from external-v2 apim (getInstitutionGeographicTaxonomiesUsingGET, getInstitutionsByGeoTaxonomiesUsingGET)
- used policy with produtId filter for getDelegationsUsingGET
=> [SELC-5432] fix: make productId param optional and rename userId param

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/AdditionalInformations.java, connector-api/src/main/java/it/pagopa/selfcare/external_api/model/onboarding/OnboardingData.java, connector/rest/docs/openapi/api-selfcare-onboarding-docs.json, infra/apim_v2/api/ms_internal_api/v1/openapi.prod.json, web/src/main/java/it/pagopa/selfcare/external_api/web/model/onboarding/AdditionalInformationsDto.java, web/src/main/java/it/pagopa/selfcare/external_api/web/model/onboarding/OnboardingProductDto.java, web/src/main/resources/swagger/swagger_en.properties
added additionalInformations to:
- OnboardingProductDto
- OnboardingData
missing data that did not allow onboarding with self-approval if the institution was a PA and the product was pagopa
=> [SELC-5539] feat: added additionalInformations to Onboarding model

app/src/main/resources/swagger/api-docs.json, infra/apim_v2/api/ms_external_api/v2/openapi.dev.json, infra/apim_v2/api/ms_external_api/v2/openapi.prod.json, infra/apim_v2/api/ms_external_api/v2/openapi.uat.json, web/src/main/java/it/pagopa/selfcare/external_api/web/controller/InstitutionV2Controller.java
userIdForAuth as param causes an restricted list of users with only that user
=> [SELC-5605] hotfix: replace userIdForAuth query param with UserId on getInstitutionUsersByProduct

src/main/java/it/pagopa/selfcare/external_api/mapper/UserMapper.java, src/main/java/it/pagopa/selfcare/external_api/model/user/OnboardedProductResponse.java, src/main/java/it/pagopa/selfcare/external_api/model/user/UserInstitutionResource.java, src/main/resources/swagger/api-docs.json, src/main/resources/swagger/swagger_en.properties, src/test/java/it/pagopa/selfcare/external_api/TestUtils.java, src/test/java/it/pagopa/selfcare/external_api/service/InstitutionServiceImplTest.java, src/test/java/it/pagopa/selfcare/external_api/service/UserServiceImplTest.java
* Updated UserMapper to include the productRoleLabel field, enabling the mapping of user product roles with descriptive labels.
* GET /users include the new productRoleLabel attribute.
This pull request introduces the usage of a new configuration option to associate Product Roles based on the InstitutionType explained in this [PR](https://github.com/pagopa/selfcare-onboarding/pull/518)
=> [SELC-5634] feat: added productRoleLabel on response GET /users

infra/apim_v2/apim.tf, pom.xml, src/main/java/it/pagopa/selfcare/external_api/mapper/UserMapper.java, src/test/java/it/pagopa/selfcare/external_api/service/InstitutionServiceImplTest.java, src/test/java/it/pagopa/selfcare/external_api/service/UserServiceImplTest.java
* Retrieve ProductRoleLabel using getProductRaw added with this [PR](https://github.com/pagopa/selfcare-onboarding/pull/531) 
*  fix MS_BACKEND_URL with external-api url on v2getUserInstitution
Retrieve ProductRoleLabel does not need to have product configuration updated in each instant
=> [SELC-5720] feat: Retrieve ProductRoleLabel using getProductRaw

infra/apim_v2/api/base_ms_url_external_policy.xml.tpl, infra/apim_v2/api/base_ms_url_external_product_policy.xml.tpl
Moving <base />  after <change /> because the creation and setting jwt session spid token should be created after oauth2.0 token validation.
=> [SELC-5775] fix: base_ms_url_external_policy to handle EXTERNAL-OAUTH2-ISSUER

infra/apim_v2/api/ms_external_api/v2/openapi.prod.json, infra/apim_v2/api/ms_external_api/v2/openapi.uat.json, infra/apim_v2/apim.tf, pom.xml
- add getUserGroupById in uat and prod external openapi
- add operationId in apim.tf
- upgrade commons version to 2.5.4
This change is required to expose getUserGroupById API in external-v2
It was tested in dev environment
=> [SELC-6068] feat: expose getUserGroupById in external-v2

src/main/java/it/pagopa/selfcare/external_api/mapper/OnboardingMapper.java, src/main/java/it/pagopa/selfcare/external_api/service/OnboardingServiceImpl.java, src/test/java/it/pagopa/selfcare/external_api/service/OnboardingServiceImplTest.java
added origin IPA for pa/import api
=> [SELC-6064] feat: added origin IPA for pa/import api

src/main/java/it/pagopa/selfcare/external_api/service/InstitutionServiceImpl.java
- fix params order in CreatePgInstitutionRequest
fix call to createPgInstitution. With the addition of istatCode, the taxId parameter is now the last one, not the third one.
=> fix params order in CreatePgInstitutionRequest

src/main/java/it/pagopa/selfcare/external_api/mapper/InstitutionMapperCustom.java
- Considering institutionType nullable in InstitutionUpdateResponse mapping
The mapper did not consider that institutionType could be null, causing an NPE when invoking Institution.valueOf
- Local tests
- Unit tests
- Integration tests
=> [SELC-7767] Fix mapping when institutionType is null
